package github.tiger.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Key".
 */
public class Key {

    private Long id;
    /** Not-null value. */
    private String path;
    /** Not-null value. */
    private String key;

    public Key() {
    }

    public Key(Long id) {
        this.id = id;
    }

    public Key(Long id, String path, String key) {
        this.id = id;
        this.path = path;
        this.key = key;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPath() {
        return path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPath(String path) {
        this.path = path;
    }

    /** Not-null value. */
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String key) {
        this.key = key;
    }

}
